### ISSUE TITLE
Argo is too slow

### ISSUE THREAD

**Issue by fkorteby** [xark-argo/argo#2]
I installed Argo on windows but the responses are taking lot of time minimum 24seconds (without any RAG/Knowledge).
But ollama with the same model is returning immediately so please check the error logs :

`INFO 2024-10-01 20:48:07.535 [26336-Thread-5] (prepare@base_handler.py:024) request api: /api/chat/say, request body: {"message":"hi","invoke_from":"debugger","bot_id":"194a25efa1524921a05ec64f0474df83","space_id":"10259718bfd444d9bce9438dfc053390","conversation_id":"391149c7-0e76-49d7-bb10-01a5ab8a9443","stream":true,"files":[],"inputs":{},"id":"194a25efa1524921a05ec64f0474df83","name":"Hakim","description":"Hakim Arabic Medicine ","mode":"chat","icon":"https://s2.loli.net/2024/09/27/NtCqJShAnMPZYw3.png","model_config":{"provider":"","model_id":"","configs":{},"model":{"provider":"ollama","name":"llama3.1:latest","mode":"chat","completion_params":{"mirostat":0,"mirostat_eta":0.1,"mirostat_tau":5,"num_ctx":32000,"num_gpu":-1,"num_predict":-1,"repeat_last_n":64,"repeat_penalty":1.1,"temperature":0.7,"top_p":0.9,"tfs_z":1,"top_k":40,"stop":[]}},"pre_prompt":"","agent_mode":{"max_iteration":4,"enabled":false,"strategy":"react","tools":[],"prompt":null},"prompt_type":"simple","network":false},"created_at":"2024-10-01T16:29:55.835739"}
WARNING 2024-10-01 20:48:25.373 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:25.551 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:25.767 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:25.960 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:26.166 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:26.345 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:26.566 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:26.767 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:26.977 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:27.191 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:27.392 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:27.580 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:27.786 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:27.981 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:28.195 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:28.417 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:28.662 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:28.853 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:29.062 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:29.259 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:29.489 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:29.714 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:29.912 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:30.137 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:30.328 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:30.552 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:30.743 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:30.943 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:31.148 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:31.380 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:31.575 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
WARNING 2024-10-01 20:48:31.803 [26336-Thread-19] (_run_coros@manager.py:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'")
INFO 2024-10-01 20:48:31.810 [26336-Thread-5] (log_request@web.py:2348) 200 POST /api/chat/say (127.0.0.1) 24275.74ms`

thanks for your help

**Comment by zmldndx** [comment]
change context window 32000 to a smaller number (like 4096), and try again.



every model support different context window, and different devices has different GPU memory size.
This parameter affects the size of context windows and GPU memory usage size.
ollama itself use a small number as default, but our original intention is to support big context window when inputing a pdf file.


anyway, we'll optimize this user experience.
thank you for asking.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xark-argo/argo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月2日(星期三) 凌晨1:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xark-argo/argo] Argo is too slow (Issue #2)





 
I installed Argo on windows but the responses are taking lot of time minimum 24seconds (without any RAG/Knowledge).
 But ollama with the same model is returning immediately so please check the error logs :
 
INFO 2024-10-01 20:48:07.535 [26336-Thread-5] ***@***.***_handler.py:024) request api: /api/chat/say, request body: {"message":"hi","invoke_from":"debugger","bot_id":"194a25efa1524921a05ec64f0474df83","space_id":"10259718bfd444d9bce9438dfc053390","conversation_id":"391149c7-0e76-49d7-bb10-01a5ab8a9443","stream":true,"files":[],"inputs":{},"id":"194a25efa1524921a05ec64f0474df83","name":"Hakim","description":"Hakim Arabic Medicine ","mode":"chat","icon":"https://s2.loli.net/2024/09/27/NtCqJShAnMPZYw3.png","model_config":{"provider":"","model_id":"","configs":{},"model":{"provider":"ollama","name":"llama3.1:latest","mode":"chat","completion_params":{"mirostat":0,"mirostat_eta":0.1,"mirostat_tau":5,"num_ctx":32000,"num_gpu":-1,"num_predict":-1,"repeat_last_n":64,"repeat_penalty":1.1,"temperature":0.7,"top_p":0.9,"tfs_z":1,"top_k":40,"stop":[]}},"pre_prompt":"","agent_mode":{"max_iteration":4,"enabled":false,"strategy":"react","tools":[],"prompt":null},"prompt_type":"simple","network":false},"created_at":"2024-10-01T16:29:55.835739"} WARNING 2024-10-01 20:48:25.373 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:25.551 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:25.767 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:25.960 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:26.166 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:26.345 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:26.566 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:26.767 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:26.977 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:27.191 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:27.392 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:27.580 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:27.786 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:27.981 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:28.195 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:28.417 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:28.662 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:28.853 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:29.062 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:29.259 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:29.489 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:29.714 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:29.912 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:30.137 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:30.328 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:30.552 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:30.743 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:30.943 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:31.148 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:31.380 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:31.575 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") WARNING 2024-10-01 20:48:31.803 [26336-Thread-19] ***@***.***:347) Error in callback coroutine: AttributeError("'NoneType' object has no attribute 'write'") INFO 2024-10-01 20:48:31.810 [26336-Thread-5] ***@***.***:2348) 200 POST /api/chat/say (127.0.0.1) 24275.74ms
 
thanks for your help

**Comment by fkorteby** [comment]
Thank you for your fast reply.

I cant find parameter "size of context window" its not visible in my version

![image](https://github.com/user-attachments/assets/d19538ed-3828-4beb-91d8-719903c9e9ef)

Thank again

**Comment by zmldndx** [comment]
> Thank you for your fast reply.
> 
> I cant find parameter "size of context window" its not visible in my version
> 
> ![image](https://private-user-images.githubusercontent.com/34208201/372741566-d19538ed-3828-4beb-91d8-719903c9e9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTEzNjIsIm5iZiI6MTcyNzg1MTA2MiwicGF0aCI6Ii8zNDIwODIwMS8zNzI3NDE1NjYtZDE5NTM4ZWQtMzgyOC00YmViLTkxZDgtNzE5OTAzYzllOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA2Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMzkyNzU0NDc5NjgyYTdjYjJlZjJhODE3ZWQ5ZmYyZGYwNmUxM2RiNGRkYTIwZWNiNTU2MDVkZTBjODU2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gd2WJFkzuV4Wh8KWU4ko-y-1YRBzwBHbEUcDzOKUPFQ)
> 
> Thank again

scroll down the options, please

**Comment by fkorteby** [comment]
Great its working fast now thank you.

**Comment by fkorteby** [comment]
Thank you
