### ISSUE TITLE
Option to force the language

### ISSUE THREAD

**Issue by fkorteby** [xark-argo/argo#3]
Sometime iam getting Chinese language with the model :

![image](https://github.com/user-attachments/assets/47fdcf69-d5b7-4ed2-b634-dc43322e5046)

Do we have any option to force the language ?

**Comment by zmldndx** [comment]
did you try to force the language in prompts?

**Comment by fkorteby** [comment]
Yes I tried but still sometimes giving me english or sometimes chinese :
![image](https://github.com/user-attachments/assets/2f51873e-bed0-40b4-8df5-eda23d6ed7e2)

**Comment by zmldndx** [comment]
how about writing prompts in Arabic language, and also you can add some examples in Arabic.

**Comment by fkorteby** [comment]
Yes its giving better results with prompt in arabic language I will try more and let you know thanks.

**Comment by fkorteby** [comment]
After changing the prompt to Arabic its working good thank you

**Comment by zmldndx** [comment]
> After changing the prompt to Arabic its working good thank you

if any other questions, feel free to join us and talk: https://discord.gg/v48c5ZCd
